# Generated by Django 4.2.5 on 2023-09-19 11:14

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
