# Generated by Django 4.2.5 on 2023-09-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
