# Generated by Django 4.2.5 on 2023-09-23 12:51

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/articles')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('views', models.IntegerField(default=0)),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
