# Generated by Django 4.2.5 on 2023-09-24 09:10

import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(100)])),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
