# Generated by Django 4.2.5 on 2023-09-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='answered',
        ),
        migrations.AddField(
            model_name='contact',
            name='situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Solved', 'Solved')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='explanation',
            field=models.TextField(max_length=500),
        ),
    ]
