# Generated by Django 4.2.5 on 2023-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='situation',
            field=models.CharField(choices=[('در انتظار', 'Pending'), ('در حال پیگیری', 'In Progress'), ('پاسخ داده شده', 'Solved')], default='Pending', max_length=30),
        ),
    ]
