# Generated by Django 4.2.5 on 2023-09-24 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_product_peresentimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcolor', models.CharField(max_length=20)),
                ('totalprice', models.CharField(max_length=12)),
                ('city', models.CharField(choices=[('0', 'استان خود را انتخاب کنید'), ('1', 'آذربایجان شرقی'), ('2', 'آذربایجان غربی'), ('3', 'اردبیل'), ('4', 'اصفهان'), ('5', 'البرز'), ('6', 'ایلام'), ('7', 'بوشهر'), ('8', 'تهران'), ('9', 'چهارمحال و بختیاری'), ('10', 'خراسان جنوبی'), ('11', 'خراسان رضوی'), ('12', 'خراسان شمالی'), ('13', 'خوزستان'), ('14', 'زنجان'), ('15', 'سمنان'), ('16', 'سیستان و بلوچستان'), ('17', 'فارس'), ('18', 'قزوین'), ('19', 'قم'), ('20', 'کردستان'), ('21', 'کرمان'), ('22', 'کرمانشاه'), ('23', 'کهگیلویه وبویراحمد'), ('24', 'گلستان'), ('25', 'گیلان'), ('26', 'لرستان'), ('27', 'مازندران'), ('28', 'مرکزی'), ('29', 'هرمزگان'), ('30', 'همدان'), ('31', 'یزد')], default='0', max_length=50)),
                ('zipcode', models.IntegerField()),
                ('fulladdress', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
