# Generated by Django 4.2.5 on 2023-09-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_city_alter_order_fulladdress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
