# Generated by Django 4.2.5 on 2023-09-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postdelivered',
            field=models.BooleanField(default=False),
        ),
    ]
