# Generated by Django 4.2.5 on 2023-09-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_postdelivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
    ]
