# Generated by Django 4.2.5 on 2023-09-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_ordertracking_order_posttracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderpreparing',
            field=models.BooleanField(default=False),
        ),
    ]
