# Generated by Django 4.2.5 on 2023-10-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
