# Generated by Django 4.2.5 on 2023-10-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_comment_approved'),
        ('order', '0019_rename_orderproducts_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_product1', to='products.product'),
        ),
    ]
