# Generated by Django 4.2.5 on 2023-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offprice',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
