# Generated by Django 4.2.5 on 2023-09-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productimage_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
    ]
